/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author alexl
 */
public class JDlgClientes extends javax.swing.JDialog {

    /**
     * Creates new form jDlgClientes
     */
    private MaskFormatter mascaraCpfFormatter, mackaraData, mackRg, maskTelefone, maskCep;
    
    public JDlgClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Cliente");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxtCodigo_afl, jTxtNome_afl, jTxtSobrenome_afl, jTxtEndereco_afl, jTxtCidade_afl,
                jTxtTelefone_afl, jTxtCep_afl,
                jFmtCpf_afl, jTxtEmail_afl, jFmtRg_afl, jTxtCep_afl, jTxtEstado_afl, jFmtDataNscT_afl,
                jTxtProfissao_afl, jChbMasculino_afl, jChbFeminino_afl, jChbAtivo_afl, jBtnCancelar, jBtnConfimar);
        
        try {
            mascaraCpfFormatter = new MaskFormatter("###.###.###-##");
            mackaraData = new MaskFormatter("##/##/####");
            mackRg = new MaskFormatter("##.###.###-#");
            maskTelefone = new MaskFormatter("(##)####-####");
            maskCep = new MaskFormatter("#####-###");
        } catch (ParseException ex) {
            
        }
        jFmtCpf_afl.setFormatterFactory(new DefaultFormatterFactory(mascaraCpfFormatter));
        jFmtDataNscT_afl.setFormatterFactory(new DefaultFormatterFactory(mackaraData));
        
        jTxtTelefone_afl.setFormatterFactory(new DefaultFormatterFactory(maskTelefone));
        jFmtRg_afl.setFormatterFactory(new DefaultFormatterFactory(mackRg));
        jTxtCep_afl.setFormatterFactory(new DefaultFormatterFactory(maskCep));
        
    }
    
    public void habilitado(boolean valor) {
        jTxtCodigo_afl.setEnabled(false);
        jTxtNome_afl.setEnabled(valor);
        
        jTxtSobrenome_afl.setEnabled(valor);
        jTxtEndereco_afl.setEnabled(valor);
        jTxtCidade_afl.setEnabled(valor);
        jTxtTelefone_afl.setEnabled(valor);
        jTxtCep_afl.setEnabled(valor);
        jFmtCpf_afl.setEnabled(valor);
        jTxtEmail_afl.setEnabled(valor);
        jFmtRg_afl.setEnabled(valor);
        
        jTxtCep_afl.setEnabled(valor);
        jTxtEstado_afl.setEnabled(valor);
        jFmtDataNscT_afl.setEnabled(false);
        jTxtProfissao_afl.setEnabled(valor);
        jChbMasculino_afl.setEnabled(valor);
        jChbFeminino_afl.setEnabled(valor);
        jChbAtivo_afl.setEnabled(valor);
        
        jBtnCancelar.setEnabled(valor);
        jBtnConfimar.setEnabled(valor);
        jBtnExcluir.setEnabled(!valor);
        jBtnAlterar.setEnabled(!valor);
        jBtnIncluir.setEnabled(!valor);
        jBtnPesquisar.setEnabled(!valor);
    }
    
    public void limparCampos() {
        jTxtCodigo_afl.setText("");
        jTxtNome_afl.setText("");
        jTxtSobrenome_afl.setText("");
        jTxtEndereco_afl.setText("");
        jTxtCidade_afl.setText("");
        jTxtTelefone_afl.setText("");
        jTxtCep_afl.setText("");
        jFmtCpf_afl.setText("");
        jTxtEmail_afl.setText("");
        jFmtRg_afl.setText("");
        jTxtEstado_afl.setText("");
        jFmtDataNscT_afl.setText("");
        jTxtProfissao_afl.setText("");
        jChbMasculino_afl.setSelected(false);
        jChbFeminino_afl.setSelected(false);
        jChbAtivo_afl.setSelected(false);
        
    }

//    
//    ERRO TRUNCATION SQL
//ALTER TABLE clientes_afl MODIFY telefone_afl VARCHAR(15);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTxtNome_afl = new javax.swing.JTextField();
        jTxtSobrenome_afl = new javax.swing.JTextField();
        jTxtEndereco_afl = new javax.swing.JTextField();
        jTxtCidade_afl = new javax.swing.JTextField();
        jTxtEstado_afl = new javax.swing.JTextField();
        jFmtCpf_afl = new javax.swing.JFormattedTextField();
        jFmtRg_afl = new javax.swing.JFormattedTextField();
        jFmtDataNscT_afl = new javax.swing.JFormattedTextField();
        jTxtCep_afl = new javax.swing.JFormattedTextField();
        jTxtEmail_afl = new javax.swing.JTextField();
        jTxtProfissao_afl = new javax.swing.JTextField();
        jChbMasculino_afl = new javax.swing.JCheckBox();
        jChbFeminino_afl = new javax.swing.JCheckBox();
        jChbAtivo_afl = new javax.swing.JCheckBox();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfimar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jTxtCodigo_afl = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTxtTelefone_afl = new javax.swing.JFormattedTextField();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Sobrenome");

        jLabel3.setText("Cidade");

        jLabel4.setText("Endereço");

        jLabel5.setText("Estado");

        jLabel6.setText("C.E.P");

        jLabel7.setText("Telefone");

        jLabel9.setText("Email");

        jLabel10.setText("Data de Nascimento");

        jLabel11.setText("CPF");

        jLabel12.setText("RG");

        jLabel13.setText("Profissão");

        jLabel14.setText("Gênero");

        jLabel15.setText("Status");

        jTxtEndereco_afl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEndereco_aflActionPerformed(evt);
            }
        });

        jTxtCidade_afl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCidade_aflActionPerformed(evt);
            }
        });

        jFmtRg_afl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtRg_aflActionPerformed(evt);
            }
        });

        jTxtEmail_afl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmail_aflActionPerformed(evt);
            }
        });

        jChbMasculino_afl.setText("Masculino");

        jChbFeminino_afl.setText("Feminino");

        jChbAtivo_afl.setText("Ativo");

        jBtnIncluir.setBackground(new java.awt.Color(153, 255, 255));
        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setBackground(new java.awt.Color(255, 0, 0));
        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfimar.setBackground(new java.awt.Color(51, 255, 51));
        jBtnConfimar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/confirmar.png"))); // NOI18N
        jBtnConfimar.setText("Confimar");
        jBtnConfimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfimarActionPerformed(evt);
            }
        });

        jBtnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setBackground(new java.awt.Color(153, 255, 255));
        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLabel16.setText("Codigo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFmtRg_afl, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                    .addComponent(jFmtDataNscT_afl)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtProfissao_afl, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                    .addComponent(jFmtCpf_afl)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(142, 142, 142)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jChbMasculino_afl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jChbFeminino_afl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jChbAtivo_afl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtCodigo_afl, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTxtEndereco_afl, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                    .addComponent(jTxtNome_afl)
                                    .addComponent(jTxtEstado_afl)
                                    .addComponent(jTxtTelefone_afl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxtSobrenome_afl, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                        .addComponent(jTxtCidade_afl)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtCep_afl)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtEmail_afl)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConfimar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnPesquisar)
                        .addGap(0, 54, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtNome_afl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jTxtSobrenome_afl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtEndereco_afl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jTxtCidade_afl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtCep_afl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jTxtEstado_afl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtEmail_afl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTxtTelefone_afl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFmtDataNscT_afl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jFmtCpf_afl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtRg_afl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtProfissao_afl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChbMasculino_afl)
                    .addComponent(jChbFeminino_afl)
                    .addComponent(jChbAtivo_afl)
                    .addComponent(jTxtCodigo_afl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfimar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtEndereco_aflActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEndereco_aflActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEndereco_aflActionPerformed

    private void jTxtEmail_aflActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmail_aflActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmail_aflActionPerformed

    private void jFmtRg_aflActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtRg_aflActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtRg_aflActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        Util.habilitar(true, jTxtCodigo_afl, jTxtNome_afl, jTxtSobrenome_afl, jTxtEndereco_afl, jTxtCidade_afl,
                jTxtTelefone_afl, jTxtCep_afl,
                jFmtCpf_afl, jTxtEmail_afl, jFmtRg_afl, jTxtCep_afl, jTxtEstado_afl, jFmtDataNscT_afl,
                jTxtProfissao_afl, jChbMasculino_afl, jChbFeminino_afl, jChbAtivo_afl, jBtnCancelar, jBtnConfimar);        // TODO add your handling code here:

        Util.habilitar(false, jBtnIncluir, jBtnExcluir, jBtnPesquisar, jBtnAlterar);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jTxtCidade_aflActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCidade_aflActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCidade_aflActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:

        Util.habilitar(true, jTxtCodigo_afl, jTxtNome_afl, jTxtSobrenome_afl, jTxtEndereco_afl, jTxtCidade_afl,
                jTxtTelefone_afl, jTxtCep_afl,
                jFmtCpf_afl, jTxtEmail_afl, jFmtRg_afl, jTxtCep_afl, jTxtEstado_afl, jFmtDataNscT_afl,
                jTxtProfissao_afl, jChbMasculino_afl, jChbFeminino_afl, jChbAtivo_afl, jBtnCancelar, jBtnConfimar);
        Util.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        
        jTxtNome_afl.grabFocus();

    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtCodigo_afl, jTxtNome_afl, jTxtSobrenome_afl, jTxtEndereco_afl, jTxtCidade_afl,
                jTxtTelefone_afl, jTxtCep_afl,
                jFmtCpf_afl, jTxtEmail_afl, jFmtRg_afl, jTxtCep_afl, jTxtEstado_afl, jFmtDataNscT_afl,
                jTxtProfissao_afl, jChbMasculino_afl, jChbFeminino_afl, jChbAtivo_afl, jBtnCancelar, jBtnConfimar);
        
        Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        
        Util.limpar(jTxtCodigo_afl, jTxtNome_afl, jTxtSobrenome_afl, jTxtEndereco_afl, jTxtCidade_afl,
                jTxtTelefone_afl, jTxtCep_afl,
                jFmtCpf_afl, jTxtEmail_afl, jFmtRg_afl, jTxtCep_afl, jTxtEstado_afl, jFmtDataNscT_afl,
                jTxtProfissao_afl, jChbMasculino_afl, jChbFeminino_afl, jChbAtivo_afl);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnConfimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfimarActionPerformed
        // TODO add your handling code here
        
        Util.habilitar(false, jTxtCodigo_afl, jTxtNome_afl, jTxtSobrenome_afl, jTxtEndereco_afl, jTxtCidade_afl,
                jTxtTelefone_afl, jTxtCep_afl,
                jFmtCpf_afl, jTxtEmail_afl, jFmtRg_afl, jTxtCep_afl, jTxtEstado_afl, jFmtDataNscT_afl,
                jTxtProfissao_afl, jChbMasculino_afl, jChbFeminino_afl, jChbAtivo_afl, jBtnCancelar, jBtnConfimar);
        Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        

    }//GEN-LAST:event_jBtnConfimarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgClientesPesquisar cp = new JDlgClientesPesquisar(null, true);
        cp.setVisible(true);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:

        int resp = JOptionPane.showConfirmDialog(null, "Confirmar Exclusão!", "Deletar registro", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            
        }

    }//GEN-LAST:event_jBtnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgClientes dialog = new JDlgClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfimar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JCheckBox jChbAtivo_afl;
    private javax.swing.JCheckBox jChbFeminino_afl;
    private javax.swing.JCheckBox jChbMasculino_afl;
    private javax.swing.JFormattedTextField jFmtCpf_afl;
    private javax.swing.JFormattedTextField jFmtDataNscT_afl;
    private javax.swing.JFormattedTextField jFmtRg_afl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField jTxtCep_afl;
    private javax.swing.JTextField jTxtCidade_afl;
    private javax.swing.JTextField jTxtCodigo_afl;
    private javax.swing.JTextField jTxtEmail_afl;
    private javax.swing.JTextField jTxtEndereco_afl;
    private javax.swing.JTextField jTxtEstado_afl;
    private javax.swing.JTextField jTxtNome_afl;
    private javax.swing.JTextField jTxtProfissao_afl;
    private javax.swing.JTextField jTxtSobrenome_afl;
    private javax.swing.JFormattedTextField jTxtTelefone_afl;
    // End of variables declaration//GEN-END:variables
}
